/* Zvezdoboy service worker: offline play. Bump VERSION on every release. */
const VERSION='zb-2026-10-10gh';
const PRECACHE=["/play/", "/fonts/fonts.css", "/fonts/exo-2-cyrillic-600-normal.woff2", "/fonts/exo-2-cyrillic-800-normal.woff2", "/fonts/exo-2-latin-600-normal.woff2", "/fonts/exo-2-latin-800-normal.woff2", "/fonts/exo-2-latin-ext-600-normal.woff2", "/fonts/exo-2-latin-ext-800-normal.woff2", "/fonts/ibm-plex-mono-cyrillic-400-normal.woff2", "/fonts/ibm-plex-mono-cyrillic-500-normal.woff2", "/fonts/ibm-plex-mono-latin-400-normal.woff2", "/fonts/ibm-plex-mono-latin-500-normal.woff2", "/fonts/ibm-plex-mono-latin-ext-400-normal.woff2", "/fonts/ibm-plex-mono-latin-ext-500-normal.woff2", "/fonts/ibm-plex-sans-cyrillic-400-normal.woff2", "/fonts/ibm-plex-sans-cyrillic-500-normal.woff2", "/fonts/ibm-plex-sans-latin-400-normal.woff2", "/fonts/ibm-plex-sans-latin-500-normal.woff2", "/fonts/ibm-plex-sans-latin-ext-400-normal.woff2", "/fonts/ibm-plex-sans-latin-ext-500-normal.woff2", "/icons/icon-192.png", "/icons/icon-512.png", "/manifest.webmanifest","/play/peerjs.min.js","/play/p2p-v5.js","/play/fb-v3.js"];
self.addEventListener('install',e=>{e.waitUntil(caches.open(VERSION).then(c=>c.addAll(PRECACHE)).then(()=>self.skipWaiting()))});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(ks=>Promise.all(ks.filter(k=>k!==VERSION).map(k=>caches.delete(k)))).then(()=>self.clients.claim()))});
self.addEventListener('fetch',e=>{const r=e.request;if(r.method!=='GET')return;const u=new URL(r.url);if(u.origin!==location.origin)return;
 e.respondWith(caches.open(VERSION).then(async c=>{const key=u.pathname.endsWith('/play/index.html')?'/play/':r;const hit=await c.match(key,{ignoreSearch:true});
  const net=fetch(r).then(res=>{if(res.ok&&res.type==='basic')c.put(key,res.clone());return res}).catch(()=>null);
  if(hit&&r.mode!=='navigate'&&r.destination!=='script'){e.waitUntil(net);return hit}if(r.destination==='script'){const res=await net;return res||hit||Response.error()}if(r.mode==='navigate'){const res=await net;if(res)return res;if(hit)return hit}const res=await net;return res||(r.mode==='navigate'?c.match('/play/'):Response.error())}))});
